# Quantum Computing In Python

![](https://www.ias.edu/sites/default/files/styles/grid_feature_teaser/public/images/featured-thumbnails/ideas/dt_c120417.jpg)

* This Notebook will show that we can successfully simulate simple quantum computation on classical computers. Quantum computation in its simplest form can be represented by just a bunch of vector and matrix operations. After reading this post we will be ready to code simple quantum circuit in Python.

<img src="https://www.autodesk.com/products/eagle/blog/wp-content/uploads/2017/05/qubit.png)" alt="Smiley face" height="200" width="300">

* The definition of qubit lies in the center of quantum computation theory. Before we dive into the explanation of qubit, let us recall the definition of classical bit. The state of classical bit can be in two states represented by column vectors:..

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-bf3537e27e958d50f7fdeb10396e6af7_l3.svg" alt="Smiley face" height="40" width="100">


In Python they can be represented by two numpy arrays:

In [1]:
# Input data files are available in the "../input/" directory..

import numpy as np # linear algebra.
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
# print(os.listdir("..../input"))

In [2]:
# Create zero and one states..
state_zero = np.array([[1.0],[0.0]])
state_one = np.array([[0.0],[1.0]])

* Qubit can be in superposition of two states defined in Eq.(1):

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-6b29717806a32429f6008459053b6e02_l3.svg" alt="Smiley face" height="100" width="200">


* Parameters c_1 and c_2 are called probability amplitudes and are complex numbers. Their norm squares |of c_1|^2 and |c_2|^2 are probabilities that as a result of measurement of a qubit would be found in state |0} and |1}, respectively. 
* Since these are probabilities the sum of these norm squares for a given state must sum to one:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-ab025cd81091d26c1a98a65ad958635f_l3.svg" alt="Smiley face" height="100" width="200">

***A state in superposition:***

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-e7e1a2544c21c18f7faa67ef642bc920_l3.svg" alt="Smiley face" height="100" width="200">

In [3]:
# Superposition
c1 = 1.0 / 2**0.5
c2 = 1.0 / 2**0.5
state_superposition = c1 * state_zero + c2 * state_one
print(state_superposition)

[[0.70710678]
 [0.70710678]]


## Assembling qubits

Quantum computer built by IBM is made up of 16 qubits. How to describe a system composed of more than one qubit? The answer comes with the concept of tensor product and allows us to correctly describe a multi-particle quantum state. The tensor product between two states is denoted by symbol shown below and we can write an example of multi-qubit state as shown in the image

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-2b2475ecc276827f9d210ac1061c1391_l3.svg" alt="Smiley face" height="300" width="400">


Tensor product that deals with vectors and matrices is also called Kronecker product and has been implemented in Numpy. Let’s build a state \011}:

In [4]:
# Assembling qunatum states
state_three = np.kron(np.kron(state_zero, state_one), state_one)
print(state_three)

def multi_kron(*args):
    ret = np.array([[1.0]])
    for q in args:
        ret = np.kron(ret, q)
    return ret

state_multi = multi_kron(state_zero, state_one, state_one, 
                         state_one, state_zero, state_one)

print(state_multi)
print(state_multi.shape)

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
(64, 1)


The  state_multi  is 2^6=64 dimensional vector and the dimensionality of an assembled state grows exponentially with number of qubits in a system.  This illustrates the overwhelming difference between quantum and classical computers. In order to simulate 64 qubit system 2^{64}=18,446,744,073,709,551,616 complex numbers are required.

## Quantum Gates

We successfully created single and multi qubit states in Python. Now, we would like to find out how to perform various transformation of these states. The quantum gates are a way of qubits manipulation.

![](https://cdn-images-1.medium.com/max/1600/1*POeoWmy78HJDZRPgp8pVIA.png)

A state enters a gate in quantum circuit and exits as another state, thus quantum gates represent time evolution of a state describing qubits and must satisfy following criteria:

* **Must preserve norms i.e. norm squared probability amplitudes sum to one after application of gate,**
* **Must be reversible i.e. evolution of each not measured quantum state must be reversible.**

It turns out that unitary matrices meet the conditions and a trivial example is just identity matrix:


<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-2f317569ee0c99935023e17bcbe18f4e_l3.svg" alt="Smiley face" height="40" width="100">


Another example of quantum gate, this time more interesting, is Hadamard gate:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-4c69760f054bedd43c0d9446ab12b60e_l3.svg" alt="Smiley face" height="40" width="100">

![](https://www.researchgate.net/profile/Francois_Impens/publication/3409658/figure/fig1/AS:394692047982605@1471113325853/Basic-quantum-gates-and-their-matrix-representations.png)

In [5]:
# Qunatum gates
gate_H = 1.0 / 2**0.5 * np.array([[1, 1],
                                  [1, -1]])
state_new = np.dot(gate_H, state_zero)
print(state_new)

[[0.70710678]
 [0.70710678]]


A 2×2 matrix is acting on a single qubit state, 4×4 matrix on 2-qubit state, and so on. To see what is the action of Hadamard gate on |0} we need to use matrix multiplication np.dot in Python:
    
**state_new = np.dot(gate_H, state_zero)**

Notice that state_new is just a superposition state_superposition from Eq.(4):

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-b30de54cbe99c2edd232093aaa74597d_l3.svg" alt="Smiley face" height="250" width="350">

Therefore the role of Hadamard gate is to create a superposition of states!

Quantum gates can be also performed on multi-qubit states, for instance SWAP gate represented by a matrix:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-94964473b1451d7e6fb328ea9e27d825_l3.svg" alt="Smiley face" height="200" width="200">

It swaps two qubits so that an example state |01} is evolved into state |10}:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-2560282243561f175908098004e28cd8_l3.svg" alt="Smiley face" height="250" width="350">

In [6]:
gate_SWAP = np.array([[1,0,0,0],
                      [0,0,1,0],
                      [0,1,0,0],
                      [0,0,0,1]])
    
state_t0 = multi_kron(state_zero, state_one)
state_t1 = np.dot(gate_SWAP, state_t0)
print(state_t1)

[[0.]
 [0.]
 [1.]
 [0.]]


## Measurement

To get information from quantum computer we need to perform measurement. Unfortunately (or fortunately) the universe works in such a way that a qubit after measurement collapses to state |0} or |1} with given probability corresponding to probability amplitudes. Remember parameters c_1 and c_2 from Eq.(2)?.

To simulate measurement in Python, we will need objects called projectors defined as:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-49a5e1a40c1fdd0d3ee79bdaa2e37ccb_l3.svg" alt="Smiley face" height="200" width="300">


Note that {0| is just a complex conjugate of |0}. The projector P_0 applied on state |0} gives back state |0}:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-1e7766091dd65d8ec80b85050435084b_l3.svg" alt="Smiley face" height="200" width="300">

whereas applied on state |1} returns 0:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-a80c82656d2bc48227185146751789ef_l3.svg" alt="Smiley face" height="200" width="300">

due to the fact that states |0} and |1} are orthogonal, so that {0|1} vanishes. The projector P_0 applied on an arbitrary qubit state would give.:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-1bd9a6d31374b14811161594e164ed4d_l3.svg" alt="Smiley face" height="200" width="300">

so intuitively we can say that projector P_0 has something to do with checking the fraction of |0} in an arbitrary state. Indeed, the probability that qubit i of an arbitrary multi-qubit state |psi} when measured is in state |0} can be expressed as:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-e371d387c7d662ad0e855dd5973d4644_l3.svg" alt="Smiley face" height="50" width="130">


If we measure that the qubit i is in state |0} then the system just after the measurement would be in a state:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-ce0ec8ef89f5cbe3c6bd4b63e6c5181b_l3.svg" alt="Smiley face" height="50" width="100">

where the denominator is just a normalization factor thanks to which probabilities add to one.

Let’s assume we have prepared following state:

<img src="http://dkopczyk.quantee.co.uk/wp-content/ql-cache/quicklatex.com-5ce1e429e531db28038aa8e82611a390_l3.svg" alt="Smiley face" height="200" width="300">

and want to simulate in Python the measurement of first qubit.

In [7]:
gate_I = np.eye(2)
state_t0 = multi_kron(state_zero, state_one)
state_t1 = np.dot(multi_kron(gate_H, gate_I), state_t0)
print(state_t1)

[[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]]


In [8]:
# Prepare state
state = np.dot(multi_kron(gate_H, gate_H), multi_kron(state_zero, state_zero))

In [9]:
# Projectors
P0 = np.dot(state_zero, state_zero.T)
P1 = np.dot(state_one, state_one.T)

In [10]:
# Probability of first qubit being in state 0
rho = np.dot(state, state.T)
prob0 = np.trace(np.dot(multi_kron(P0, gate_I), rho))

In [11]:
# Simulate
if np.random.rand() < prob0:
    ret = 0
    state_ret = np.dot(multi_kron(P0, gate_I), state)
else:
    ret = 1
    state_ret = np.dot(multi_kron(P1, gate_I), state) 

In [12]:
# Normalize
from scipy import linalg
state_ret /= linalg.norm(state_ret)

print("Qubit Measured: \n {} \n After-Measurment State: \n {}".format(ret, state_ret))

Qubit Measured: 
 1 
 After-Measurment State: 
 [[0.        ]
 [0.        ]
 [0.70710678]
 [0.70710678]]


## References
* [IBM Builds Its Most Powerful Universal Quantum Computing Processors](https://www-03.ibm.com/press/us/en/pressrelease/52403.wss (2017)).
* N. S. Yanofsky and M. A. Mannucci, Quantum Computing for Computer Scientists, Cambridge University press (2008).